# Generated by Django 5.0.1 on 2024-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_runningsetsgoal_training_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setsgoal',
            name='rest_max',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setsgoal',
            name='rest_min',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
