# Generated by Django 5.0.1 on 2024-01-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setsgoal_rest_max_setsgoal_rest_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='days_in_microcycle',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
