# Generated by Django 5.0.1 on 2024-02-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_program_days_in_microcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingday',
            name='name',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
